# About Us
__Tushar Mittal__

Hello!
I am Tushar Mittal and I am a graduate student at Ross School of Business pursuing my Master of Business Analytics (MBAn). I am an international student from Nepal and did my undergraduate at Ramapo College of New Jersey where I double majored in Accounting and Finance. After my undergraduate, I worked at Deloitte as an Audit and Assurance Analyst in the Philadelphia office, and quickly realized that I wanted to learn more about Analytics and Data. It’s just my first semester at Ross, and I have already learnt so much! I look forward to making the best out of my time here at University of Michigan and expanding my network!

__Photo goes here__

I enjoy traveling and visiting new places and believe in giving my 💯% in whatever I do. In my free time, I like to cook, play video games, or read about new and interesting topics surrounding business and tech. Feel free to connect with me on LinkedIn!

__Maria Viera__

Recently graduated from my second bachelor's degree in Economics, I am now a current Master of Business Analytics student at Ross (University of Michigan). 

I am originally from Spain with a previous background in **Dietetics** and **Sport Nutrition**. During my time in Spain and after 6 years in the **Health** field, I moved to the United States and decided to change careers to **Economics**. 

Crossing the pond for my first time in 2019 meant starting from zero: language, culture, making friends, food, career, etc. Getting involved with the community through voluntary activities while studying English, prepared me to an **English academic level in less than two years** to start my second degree in Economics. 

As a **Military Spouse**, life changes every three years, so my option to start a new career had to be online. This lifestyle tough me *to get comfortable when being uncomfortable*. As an example, the time to move for the next assignment was in the middle of my first semester, when we had to move to England (my current home). A fun fact is that I had to study on the floor for two weeks until we got some borrowed furniture. After two years and a half, I graduated this past May 2023, and a month later I started the MBAn's program which is inspiring me to keep growing and overcome my barriers to be the best version of myself. 


__Juliet Niebylski__

I have a B.S.E. in Data Science from University of Michigan and am interested in applying data science for business. I am from Kensington, Maryland. I enjoy baking different types of desserts.
